x-server-env: &server-env
  DEBUG: 'True'
  DJANGO_SETTINGS_MODULE: config.settings


services:
# TODO:- mongodb settings
#  db:
#    image: mongo:latest
#    container_name: mongodb
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: myuser
#      MONGO_INITDB_ROOT_PASSWORD: mypassword
#      MONGO_INITDB_DATABASE: mydatabase

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    environment:
      <<: *server-env
#    depends_on:
#      - db

volumes:
  postgres_data:
