x-server-env: &server-env
  DEBUG: 'True'
  DJANGO_SETTINGS_MODULE: config.settings
  SUPERUSER_USERNAME: admin3
  SUPERUSER_EMAIL: admin3@example.com
  SUPERUSER_PASSWORD: admin3password
  WEBHOOK_URL: http://host.docker.internal:5000/remote-entity-update
  WEBHOOK_SECRET: b1RETKgYo6QeaIEDsYiUalpVoPw-XG0wfjPxmn6mNJk
  DELETE_PREVIOUS_WEBHOOKS: True


services:
  postgres_db:
    image: postgres:latest
    container_name: ti_wizard_db_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4
    ports:
      - "6397:6397"

  celery_worker:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    command: celery -A config.settings.celery:app worker -Q celery,webhooks
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    environment:
      <<: *server-env
    depends_on:
      - postgres_db
      - redis
      - celery_worker

volumes:
  postgres_data:
