x-server-env: &server-env
  DEBUG: 'True'
  DJANGO_SETTINGS_MODULE: config.settings
  SUPERUSER_USERNAME: admin3
  SUPERUSER_EMAIL: admin3@example.com
  SUPERUSER_PASSWORD: admin3password


services:
  postgres_db:
    image: postgres:latest
    container_name: ti_wizard_db_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    environment:
      <<: *server-env
    depends_on:
      - postgres_db

volumes:
  postgres_data:
