# Generated by Django 4.2.16 on 2024-11-08 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="")),
                ("description", models.TextField(default="")),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("SAML_IDP", "SAML IDP"),
                            ("SAML_SP", "SAML SP"),
                            ("OIDC_OP", "OIDC OP"),
                            ("OIDC_RP", "OIDC RP"),
                        ],
                        max_length=50,
                    ),
                ),
                ("entity_id", models.TextField(default="")),
                ("metadata_url", models.TextField(default="")),
                ("discovery_url", models.TextField(default="")),
                ("client_id", models.TextField(default="")),
                ("client_secret", models.TextField(default="")),
                ("redirect_uri", models.TextField(default="")),
                ("dynamic_registration", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("comment", models.TextField(default="")),
                ("metadata_hash", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_remote_entity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_remote_entity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
