# Generated by Django 4.2.16 on 2024-11-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remote_entities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoteentity",
            name="client_id",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="remoteentity",
            name="client_secret",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="remoteentity",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="remoteentity",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="remoteentity",
            name="discovery_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="remoteentity",
            name="entity_id",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="remoteentity",
            name="metadata_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="remoteentity",
            name="name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="remoteentity",
            name="redirect_uri",
            field=models.TextField(blank=True, default=""),
        ),
    ]
