# Generated by Django 4.2.16 on 2024-11-18 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("remote_entities", "0002_alter_remoteentity_client_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteentity",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
