# Generated by Django 4.2.16 on 2024-11-18 15:36
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    RemoteEntity = apps.get_model("remote_entities", "RemoteEntity")
    for row in RemoteEntity.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("remote_entities", "0003_remoteentity_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
