# Generated by Django 4.2.16 on 2024-11-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remote_entities", "0006_alter_remoteentity_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteentity",
            name="randomfield",
            field=models.TextField(blank=True, default="random"),
        ),
    ]
