# Generated by Django 4.2.16 on 2024-11-20 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("remote_entities", "0007_remoteentity_randomfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remoteentity",
            name="randomfield",
        ),
    ]
