# Generated by Django 4.2.16 on 2024-11-21 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("remote_entities", "0008_remove_remoteentity_randomfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remoteentity",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
