# Generated by Django 4.2.16 on 2024-11-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remote_entities", "0009_alter_remoteentity_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remoteentity",
            name="uuid",
        )
    ]
