# Generated by Django 4.2.16 on 2024-11-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("remote_entities", "0010_remove_remoteentity_uuid_remoteentity_id_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteentity",
            name="id_hash",
            field=models.CharField(max_length=64, blank=True, null=True, unique=True),
        ),
    ]
